name: Strava Bot Cron

on:
  schedule:
    - cron: '*/5 * * * *'  # cada 5 minutos
  workflow_dispatch: # también puedes lanzarlo a mano desde GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Ejecutar el bot Strava
      - name: Run Strava Bot
        run: node bot.js
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
          NUM_ACTIVITIES: 1   # cuántas actividades actualizar
