name: Strava Bot Cron

on:
  schedule:
    - cron: '* * * * *'  # cada minuto
  workflow_dispatch: # permite ejecutar manualmente

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Strava Bot
        env:
          STRAVA_ACCESS_TOKEN: ${{ secrets.STRAVA_ACCESS_TOKEN }}
          NUM_ACTIVITIES: 1   # actualizar solo 1 actividad
        run: node bot.js
